# permissions for end users to view probes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: probe-viewer-role
rules:
- apiGroups:
  - probe.prober.io
  resources:
  - probes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - probe.prober.io
  resources:
  - probes/status
  verbs:
  - get
