# permissions for end users to edit probes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: probe-editor-role
rules:
- apiGroups:
  - probe.prober.io
  resources:
  - probes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - probe.prober.io
  resources:
  - probes/status
  verbs:
  - get
